name: Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:13.11.0

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment (Add Yarn to PATH)
        run: |
          echo "/usr/local/bin" >> $GITHUB_PATH
          # Nota: A verificação "if command -v yarn" e o "echo Updated PATH" foram removidos para simplificar.
          # Presumimos que funcionou com sucesso. Se der problema no futuro, reintroduzir.

      - name: Install curl in container
        run: |
          apt-get update && apt-get install -y curl

      - name: Install Dependencies
        run: yarn install --legacy-peer-deps

      - name: Start Application and Backend
        run: |
          echo "Starting application and backend in background..."
          # Inicia o app em background. A saída vai para app_logs.log
          nohup bash -c "yarn dev" > app_logs.log 2>&1 &
          
          echo "Waiting for frontend to be available at http://localhost:3000 (up to 5 minutes)..."
          # Permanece com um retry longo para garantir a inicialização completa.
          curl -s --head --fail http://localhost:3000 --retry 60 --retry-delay 5 || {
            echo "Frontend did not become available within timeout!";
            echo "--- Application Logs (from yarn dev) ---";
            # Mantém um sleep para garantir que o log seja escrito antes de ser lido em caso de falha.
            sleep 15 
            if [ -s app_logs.log ]; then
              cat app_logs.log;
            else
              echo "app_logs.log is empty or does not exist."
            fi
            echo "--- End Application Logs ---"
            exit 1;
          }

          echo "Frontend is up. Giving it a few more seconds to fully load before tests..."
          sleep 15 
          echo "Ready to run Cypress tests."

      - name: Run Cypress E2E Tests
        run: npx cypress run
        
    env:
      CYPRESS_BASE_URL: http://localhost:3000